### ISSUE TITLE
How do I get libugpio?

### ISSUE THREAD

**Issue by Cacowned** [OnionIoT/c-cross-compile-example#1]
Per the title, the wiki page briefly mentions needing libugpio, but how do I get that for cross-compiling this example?

**Comment by greenbreakfast** [comment]
this will be covered in detail in an upcoming 2-bullet tuesday tip. In the meantime, you can see [our recent 2BT tip on configuring the LEDE build system on your computer](https://onion.io/2bt-cross-compiling-c-programs-part-1/), this will build `libugpio` for you.

**Comment by nicolapalavecino** [comment]
When you follow the steps on https://docs.onion.io/omega2-docs/cross-compiling.html#cross-compiling you don't get the libugpio with the source code. You should tick the library when you do `make menuconfig`
