### ISSUE TITLE
xCompile.sh without library

### ISSUE THREAD

**Issue by Kalbo85** [OnionIoT/c-cross-compile-example#2]
Hi,
just trying to cross compile using the file xCompile.sh.
`sh xCompile.sh -buildroot /root/source -lib`

how to let the compiler knows that it doesn't need a library?
and if the compliler would need two different Libraries?

Thanks in advance!

**Comment by greenbreakfast** [comment]
> how to let the compiler knows that it doesn't need a library?

Modify line 10 in the Makefile to remove the `-l$(LIB)`, and run the xCompile.sh script without the `-lib` argument.

> and if the compliler would need two different Libraries?

Add the additional libraries to the `-lib` argument input. Just remember to surround the input with quotes, and to add `-l` to each library after the first one.

For example, say you wanted to use xCompile and link the ugpio, oniondebug, and onioni2c libraries. The command would look like this: 

```
sh xCompile.sh -buildroot /home/ubuntu/source -lib "ugpio -loniondebug -lonioni2c"
```

**Comment by Kalbo85** [comment]
Thanks!
I'ḿ trying to understand how cross-compiling works, and xCompile is helping more than every other information or explanations I found.
