### ISSUE TITLE
Executable does not run on the Omega

### ISSUE THREAD

**Issue by cryptax** [OnionIoT/c-cross-compile-example#4]
Hi, 
I have compiled the cross-compiler, and then tested with this example. It built `gpioRead` without any problem. Unfortunately, the executable does not run on my Onion Omega! What's wrong?

```
root@Omega-0431:~# ./gpioRead 
./gpioRead: line 1: EL@4�t4: not found
./gpioRead: line 26: syntax error: unexpected "(" (expecting ")")
```

- Device: Onion **Omega**
- Firmware **0.1.4 b336**
- Compile host: I used the Docker container, and updated (feeds and git)
- Target system: **MediaTek Ralink MIPS**
- Subtarget: **MT76x8 based boards**
- Target profile: **Multiple targets**
- Target devices: **Onion Omega2** (I didn't see *Omega*, actually looks like only Omega 2 exists in products)

The generated `gpioRead` is for MIPS architecture, and seems correct:

```
# file gpioRead
gpioRead: ELF 32-bit LSB executable, MIPS, MIPS32 rel2 version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-mipsel-sf.so.1, with debug_info, not stripped
# ls -lh gpioRead
-rwxr-xr-x 1 root root 9.5K Jul 16 09:01 gpioRead
```

On the Omega,

```
# uname -a
Linux Omega-0431 3.18.44 #3 Wed Oct 26 23:09:35 UTC 2016 mips GNU/Linux

# dmesg | grep -i onion
[    0.000000] Kernel command line:  board=ONION-OMEGA  console=ttyATH0,115200 rootfstype=squashfs,jffs2 noinitrd
[    0.100000] MIPS: machine is Onion Omega
```

**Comment by cryptax** [comment]
I don't have `/lib/ld-musl-mipsel-sf.so.1` on my Omega, which is likely to cause the problem. 
On the cross compiling host, this file is inside the target's `root-ramips/lib` directory, but I probably missed how I am meant to make this available on the Omega...

**Comment by greenbreakfast** [comment]
@cryptax This repo is meant to provide a cross-compilation example for the Onion Omega**2**. It will not work for the original Omega.

The Original Omega, while great in it’s time, has not been produced since 2015. We strongly recommend upgrading to the Omega2 family, the hardware is more powerful, it’s a more mature product, and we've done a lot of work to make it a great IoT computer.

**Comment by cryptax** [comment]
arg, ok, would be useful to keep the mention that Onion Omega used to exist in your documentation, because as I saw no trace of it, I thought Omega == Omega2 ;-)
Thx!
